// Everything the roommates say in speech bubbles. Keyed by situation, action id, personality or crew member.

export const LINES = {
  arrival: [
    'Lovely place. Weird number of waivers.', 'I give this household three business days.', 'The rent is low. Suspiciously low.',
    'Finally. A fresh start with worse people.', 'Why does the welcome mat say LEAVE?', 'I already hate the wallpaper. And you.',
    'The previous tenants left in a hurry. And a hearse.', 'Great location. Close to the cemetery. Very convenient.',
    'Who designed this house, an insurance company?', 'I brought my own knives. For cooking. Mostly.',
  ],
  idle: [
    'Somebody used my mug. Somebody will pay.', 'I labelled my yoghurt. Legally, it is a contract.',
    'The Wi-Fi password is "ChangeThisNow". Nobody has.', 'I can hear someone chewing from two rooms away.',
    'Who keeps leaving one sheet of toilet paper? Psychopath.', 'This house smells like unresolved conflict.',
    'I have started a spreadsheet of grievances. Tab six is you.', 'The thermostat is set to "passive aggressive".',
    'Every door in this house creaks in a judgemental tone.', 'I miss my old roommate. The one I buried. Kidding. Mostly.',
    'Chore wheel? I prefer chore roulette.', 'If I disappear, check the cleaning rota first.',
    'I pay a third of the rent and get none of the silence.', 'The walls here are thin and full of opinions.',
    'Someone keeps alphabetising my cereal. I know it is a threat.', 'The fridge hums in a tone I find personal.',
    'Our house plant has seen things. It is not doing well.', 'I found a hair in the butter. It is not mine. It is not human.',
    'The group chat has been silent for an hour. Something is planned.', 'I have hidden the good scissors. From all of you.',
    'Who set the smoke alarm to "encouraging"?', 'The bins go out Thursday. So might you.',
    'I would move out, but the deposit is emotionally non-refundable.', 'There is a draft in here. Or a ghost. Either way, rude.',
  ],
  fire: [
    'Is the smoke alarm being sarcastic?', 'This is NOT what I meant by a housewarming.', 'The deposit is absolutely gone.',
    'Stop, drop and — no, I refuse to roll on this carpet.', 'Everything is fine. The ceiling is just very orange.',
    'Who put the house on the barbecue setting?', 'I KNEW that candle had intentions.', 'Is this a good time to mention I never got insurance?',
    'Hot tip: RUN.', 'My eyebrows have left the building.',
  ],
  trapped: ['I would like to unsubscribe from this floor.', 'Is this covered by the cleaning rota?', 'Who puts a bear trap next to the petunias?!', 'My leg has filed for divorce.', 'This is fine. This is a fine lawn.'],
  stuck: ['Who put the exit behind a paywall?', 'The ladder has left the group chat.', 'I would like to speak to the pool manager.', 'Swimming is just drowning with extra steps.', 'LADDER. LADDER. ANYONE. LADDER.'],
  poison: [
    'The leftovers have a very long finish.', 'Was the expiry date a threat?', 'My stomach has filed a formal complaint.',
    'Everything tastes faintly of almonds and regret.', 'I think the soup is looking at me.', 'Is green a normal colour for a tongue?',
    'I have reached the "writing a will on a napkin" stage.',
  ],
  gassy: ['That was the floorboards. All of them.', 'I have become the open-plan problem.', 'Grandma, what did you PUT in this?', 'Open a window. Open all of them.', 'I am a biological weapon now.'],
  hunger: ['Whose name is on the emergency cheese?', 'I could eat a horse. Is that what is in the fridge?', 'My stomach is louder than the TV.', 'If I faint, eat me last.', 'Is it cannibalism if we are just roommates?'],
  energy: ['My personality is running on 2%.', 'Wake me when the lease expires.', 'I am not lazy, I am in low-power mode.', 'I could sleep standing up. I might be.'],
  suspicious: [
    'I am starting a group chat without you.', 'Why does the insurance agent know our names?', 'That is the third extremely normal accident.',
    'Is anyone else sleeping with one eye open?', 'I have started tasting my food with a teaspoon first.', 'The neighbours have stopped waving.',
    'Funny how the accidents only happen to the annoying ones.',
  ],
  death: [
    'So... is their shelf in the fridge available?', 'Do we split their share of the Wi-Fi bill?', 'I am not telling the landlord.',
    'This is going to ruin our inspection score.', 'Dibs on their room.', 'I will say a few words. Mostly about the dishes they left.',
    'Should we... cancel their Netflix?', 'Well. That settles the thermostat debate.', 'I always said they would go out doing something stupid.',
    'Their plant is mine now. The plant deserves better.',
  ],
  immortal: ['Cute. Anyway, where were we?', 'Death and I have a scheduling conflict.', 'My plot armour is dry-clean only.', 'I have died before. It was boring.', 'Tell the Reaper to book an appointment.'],
  meteor: ['That is a very aggressive shooting star.', 'I wished for SPACE. Personal space.', 'Is that star getting BIGGER?', 'Oh, come ON, universe.'],
  chat: [
    'We should really have a house meeting.', 'Which one of us is the red flag?', 'The walls are thin. So is my patience.',
    'So what do you do? Besides annoy me.', 'I love what you have done with your hair. It is so brave.',
    'Have you ever thought about moving? Far? Soon?', 'We should hang out more. Supervised.', 'Honestly? You are my favourite roommate. Low bar.',
  ],
  insult: [
    'You have the energy of a damp receipt.', 'Even the mould wants a different roommate.', 'Your vibe has a cancellation fee.',
    'You are the human version of a reply-all.', 'I have met more charming parking tickets.', 'You chew like you are angry at the food.',
    'If I wanted to hear from you, I would have read your notes.', 'You are why the shampoo bottles have instructions.',
  ],
  fight: ['We are settling the thermostat debate.', 'Consider this constructive feedback.', 'This is for the yoghurt!', 'Nobody touches my labelled shelf!', 'Hold my towel.'],
  cook: ['The recipe says medium. I feel extreme.', 'Smoke is just seasoning with ambition.', 'How hot should the pan be? Yes.', 'Is the oil supposed to be on fire already?', 'I cook like I live: dangerously.'],
  grill: ['Rare, medium, or legally complicated?', 'Is the grill meant to be screaming?', 'Nothing says summer like singed eyebrows.'],
  snack: ['If it glows, it counts as a vegetable.', 'Someone wrote DO NOT EAT. A serving suggestion.', 'This container says "NOT YOURS". Delicious.', 'Mystery meat. My favourite genre.'],
  swim: ['Finally, a room without opinions.', 'I checked the water. It is definitely wet.', 'Nobody pee in the pool. I am looking at you.', 'The water is lovely. Suspiciously lovely.'],
  bath: ['A little self-care. What could possibly happen?', 'Bubble bath. Candles. Radio on the edge. Perfect.', 'Do not knock. I mean it.'],
  radio: ['Nothing relaxes me like electricity near water.', 'Turn it up! Wait, not like that—'],
  repair: ['I watched half a tutorial. We are fine.', 'Red wire, blue wire. Rhymes with fire.', 'How hard can wiring be? Asking for my obituary.'],
  read: ['Chapter one: recognising warning signs.', 'This book is about a house exactly like ours. It does not end well.', 'Reading improves the mind. Mine is fine as it is.'],
  watch: ['Reality TV makes our house seem healthy.', 'A true crime show! Taking notes.', 'This documentary is about poisons. How relaxing.'],
  darkarts: ['The terms and conditions want my soul. Standard.', 'Step one: draw a circle. Step two: regret.', 'This forum has some VERY specific advice.'],
  devgame: ['It is not a bug. It is psychological horror.', 'Patch notes: removed the ending.', 'Three people will love this. One will review it.'],
  playtesting: ['Where is the save button? WHERE IS IT?', 'Level 40 is just a tax form.', 'I think the crow is judging me.'],
  gaslight: ['We never had a ladder. You imagined stairs.', 'That is not a red flag. That is mood lighting.', 'You are remembering it wrong. Again.', 'I never said that. Are you feeling alright?'],
  triangulate: ['I should not say this. Anyway, listen.', 'I am only telling you because I care. And because it is juicy.', 'Guess who has been talking about you?'],
  smear: ['It is not gossip if I made a slideshow.', 'I heard they steal from the fridge. I also started that.', 'Everybody knows. Now.'],
  lovebomb: ['We are soulmates. What is your PIN?', 'I have never met anyone like you. Sign here.', 'You are PERFECT. Do not change. Do not ask questions.'],
  lure: ['Come with me. Ignore the ominous music.', 'This way, darling. Mind the flames.', 'Follow me. Trust me. Mostly follow me.'],
  guilttrip: ['After everything I have almost done for you.', 'No, no, it is fine. I will just starve. Quietly. Loudly.', 'I am not upset. I am disappointed. And hungry.'],
  scene: ['I am being VERY reasonable, dramatically.', 'Everyone LOOK at how calm I am!', 'I need an audience for this breakdown.'],
  silent: ['...', '. . .', '*pointed silence*'],
  story: ['To understand my dream, we start in 2004.', 'Anyway, that was just the prequel.', 'Long story short: chapter seventeen.', 'Where was I? Oh yes, the beginning.', 'This next bit is really important. Also the bit after.'],
  joke: ['Our lease has a survival clause. Fine print.', 'Why did the roommate cross the road? The house was on fire.', 'I would tell you a poison joke, but you would not get it. Yet.'],
  drink: ['Try this. Family recipe.', 'Drink up. It is good for you. Briefly.', 'I made you a little something. Bottoms up.'],
  flirtfire: ['Is it hot in here, or is it the house?', 'Take your time. Really. No rush.', 'Do you come to fires often?', 'Tell me about your hose. Slowly.'],
  coffee: ['Milk? Sugar? Alibi?', 'Sit, relax, stop looking at things.', 'Fresh pot. Nothing in it. Promise.'],
  charmdet: ['Officer, I am a very trustworthy person. Look at me.', 'Is that a warrant, or are you pleased to see me?', 'You look tired. Let me walk you to your car.'],
  ramble: ['So in 2004 I had this dream, right?', 'This part is crucial. So is the next part.', 'Where was I? Oh yes, the beginning.'],
  spoofradio: ['Dispatch has some urgent news for you. I wrote it.', 'All units, report to literally anywhere else.', 'Beep boop. Police business.'],
  note: ['Per my last extremely passive-aggressive note.', 'The dishes are not soaking. They are evolving.', 'Kindly. KINDLY. Underlined.'],
  narcissist: [
    'The lighting here does not respect my journey.', 'I am the main character. You are overheads.', 'Mirror, mirror — never mind, I already know.',
    'I would apologise, but I am never wrong.', 'Everyone here should be grateful I moved in.', 'My flaws are what make me perfect.',
    'Is this about me? It is usually about me.', 'I do not have enemies. I have audiences.', 'Humble? I invented humble. I am the best at it.',
  ],
  schemer: [
    'My alibi has an alibi.', 'I call it conflict optimisation.', 'Every friendship is a long con with snacks.',
    'I never lie. I edit the truth for length.', 'Trust is just a vulnerability with good PR.', 'Plan A was friendship. Plan B is better.',
    'I keep my friends close and my receipts closer.', 'Everyone here is a chess piece. I am the hand.', 'Rules are just suggestions with lawyers.',
  ],
  drama: [
    'I need privacy. And an audience.', 'Nobody panic until I have changed outfits.', 'This is the WORST day of my life. Today.',
    'I am fine. I am FINE. Does anyone want to hear why I am not fine?', 'Somebody breathed near my shelf.', 'I am not crying, I am performing.',
    'This house has no respect for my arc.', 'I have had a breakdown and a breakthrough. Before lunch.',
  ],
  vampire: [
    'Quick question. Do you have six hours?', 'I am an empath. Your energy is now mine.', 'You look tired. I will tell you about my problems.',
    'I am not needy. I just need everyone.', 'Could you hold this conversation? For the rest of your life?', 'I feel so drained. Come closer.',
    'Let me tell you about my feelings. All of them. Chronologically.',
  ],
  charmer: ['I am a catch. Read that as a warning.', 'Trust me. Terrible idea, but do it.', 'Everyone falls for me. Some of them literally.', 'I get away with everything. It is exhausting.'],
  hacker: ['Have you tried turning the household off?', 'I put the smart fridge on probation.', 'Your password is your birthday. It was.', 'I have root access to the toaster.'],
  // The named crew get their own material.
  asraa: [
    'Technically I am a doctor. Of chemistry. Of consequences.', 'Relax, it is organic. Most poisons are.',
    'I am billing the law firm for this conversation.', 'Untraceable is my love language.', 'I have testified in forty trials. Never as the defendant.',
    'Beauty fades. My toxicology report does not.', 'Would you like a drink? It is very... bespoke.',
    'Objection. I am far too pretty to be guilty.', 'I did my thesis on almonds. Ask me why.', 'The coroner and I have an understanding.',
    'Nobody searches the handbag of the expert witness.', 'Chemistry is just cooking where the guests do not wake up.',
  ],
  daniel: [
    'My new game has no tutorial. Or mercy.', 'I am not antisocial. I am in early access.', 'The smart lock does what I tell it. Unlike people.',
    'Death keeps crashing on my machine.', 'I speedran the lease agreement.', 'This house has more bugs than my game. I put most of them there.',
    'Asraa, did you see my new build? It deletes people. Emotionally.', 'Immortality is just an extremely long session.',
  ],
  adam: [
    'So anyway, that reminds me of a story.', 'Do not worry, this one only has nine parts.', 'I will keep it short. That was a joke. It will not be short.',
    'Where was I? Right. 1997.', 'Have I told you about my sourdough? Settle in.', 'Pull up a chair. And a sleeping bag.',
    'Interesting fact about gravel: there are many.', 'And THAT is only the introduction.',
  ],
};

export const REPLIES = {
  chat: ['Can this meeting be an email?', 'I miss living alone. With my problems.', 'Wow. Great. Anyway.', 'I will think about it. I will not.'],
  insult: ['I am putting that in the group chat.', 'Bold words from someone who owns that towel.', 'Noted. Revenge scheduled.', 'Say that again and see what happens to your yoghurt.'],
  story: ['I have aged during this sentence.', 'Blink twice if the story has an ending.', 'Please. I have a family. Somewhere.', 'Is there an intermission?'],
  gaslight: ['I am fairly sure I remember a ladder.', 'I need a second opinion. From a plant.', 'Am I... imagining things?'],
  lovebomb: ['This feels like a subscription trap.', 'Nobody has ever said that to me. Suspicious.', 'Is this a pyramid scheme?'],
  note: ['Your handwriting also needs a rota.', 'I left a note about your note.', 'A laminated note? You psychopath.'],
  joke: ['I should not laugh. I cannot stop.', 'That is so wrong. Tell it again.'],
  drink: ['It smells like almonds. Is that normal?', 'Cheers! Why are you not drinking?'],
};
