// Everything the roommates say in speech bubbles. Keyed by situation, action id, personality or crew member.

export const LINES = {
  arrival: [
    'Lovely place. Weird number of waivers.', 'I give this household three business days.', 'The rent is low. Suspiciously low.',
    'Finally. A fresh start with worse people.', 'Why does the welcome mat say LEAVE?', 'I already hate the wallpaper. And you.',
    'The previous tenants left in a hurry. And a hearse.', 'Great location. Close to the cemetery. Very convenient.',
    'Who designed this house, an insurance company?', 'I brought my own knives. For cooking. Mostly.',
  ],
  idle: [
    'Somebody used my mug. Somebody will pay.', 'I labelled my yoghurt. Legally, it is a contract.',
    'The Wi-Fi password is "ChangeThisNow". Nobody has.', 'I can hear someone chewing from two rooms away.',
    'Who keeps leaving one sheet of toilet paper? Psychopath.', 'This house smells like unresolved conflict.',
    'I have started a spreadsheet of grievances. Tab six is you.', 'The thermostat is set to "passive aggressive".',
    'Every door in this house creaks in a judgemental tone.', 'I miss my old roommate. The one I buried. Kidding. Mostly.',
    'Chore wheel? I prefer chore roulette.', 'If I disappear, check the cleaning rota first.',
    'I pay a third of the rent and get none of the silence.', 'The walls here are thin and full of opinions.',
    'Someone keeps alphabetising my cereal. I know it is a threat.', 'The fridge hums in a tone I find personal.',
    'Our house plant has seen things. It is not doing well.', 'I found a hair in the butter. It is not mine. It is not human.',
    'The group chat has been silent for an hour. Something is planned.', 'I have hidden the good scissors. From all of you.',
    'Who set the smoke alarm to "encouraging"?', 'The bins go out Thursday. So might you.',
    'I would move out, but the deposit is emotionally non-refundable.', 'There is a draft in here. Or a ghost. Either way, rude.',
  ],
  fire: [
    'Is the smoke alarm being sarcastic?', 'This is NOT what I meant by a housewarming.', 'The deposit is absolutely gone.',
    'Stop, drop and — no, I refuse to roll on this carpet.', 'Everything is fine. The ceiling is just very orange.',
    'Who put the house on the barbecue setting?', 'I KNEW that candle had intentions.', 'Is this a good time to mention I never got insurance?',
    'Hot tip: RUN.', 'My eyebrows have left the building.',
  ],
  trapped: ['I would like to unsubscribe from this floor.', 'Is this covered by the cleaning rota?', 'Who puts a bear trap next to the petunias?!', 'My leg has filed for divorce.', 'This is fine. This is a fine lawn.'],
  stuck: ['Who put the exit behind a paywall?', 'The ladder has left the group chat.', 'I would like to speak to the pool manager.', 'Swimming is just drowning with extra steps.', 'LADDER. LADDER. ANYONE. LADDER.'],
  poison: [
    'The leftovers have a very long finish.', 'Was the expiry date a threat?', 'My stomach has filed a formal complaint.',
    'Everything tastes faintly of almonds and regret.', 'I think the soup is looking at me.', 'Is green a normal colour for a tongue?',
    'I have reached the "writing a will on a napkin" stage.',
  ],
  gassy: ['That was the floorboards. All of them.', 'I have become the open-plan problem.', 'Grandma, what did you PUT in this?', 'Open a window. Open all of them.', 'I am a biological weapon now.'],
  hunger: ['Whose name is on the emergency cheese?', 'I could eat a horse. Is that what is in the fridge?', 'My stomach is louder than the TV.', 'If I faint, eat me last.', 'Is it cannibalism if we are just roommates?'],
  energy: ['My personality is running on 2%.', 'Wake me when the lease expires.', 'I am not lazy, I am in low-power mode.', 'I could sleep standing up. I might be.'],
  suspicious: [
    'I am starting a group chat without you.', 'Why does the insurance agent know our names?', 'That is the third extremely normal accident.',
    'Is anyone else sleeping with one eye open?', 'I have started tasting my food with a teaspoon first.', 'The neighbours have stopped waving.',
    'Funny how the accidents only happen to the annoying ones.',
  ],
  death: [
    'So... is their shelf in the fridge available?', 'Do we split their share of the Wi-Fi bill?', 'I am not telling the landlord.',
    'This is going to ruin our inspection score.', 'Dibs on their room.', 'I will say a few words. Mostly about the dishes they left.',
    'Should we... cancel their Netflix?', 'Well. That settles the thermostat debate.', 'I always said they would go out doing something stupid.',
    'Their plant is mine now. The plant deserves better.',
  ],
  immortal: ['Cute. Anyway, where were we?', 'Death and I have a scheduling conflict.', 'My plot armour is dry-clean only.', 'I have died before. It was boring.', 'Tell the Reaper to book an appointment.'],
  meteor: ['That is a very aggressive shooting star.', 'I wished for SPACE. Personal space.', 'Is that star getting BIGGER?', 'Oh, come ON, universe.'],
  chat: [
    'We should really have a house meeting.', 'Which one of us is the red flag?', 'The walls are thin. So is my patience.',
    'So what do you do? Besides annoy me.', 'I love what you have done with your hair. It is so brave.',
    'Have you ever thought about moving? Far? Soon?', 'We should hang out more. Supervised.', 'Honestly? You are my favourite roommate. Low bar.',
  ],
  insult: [
    'You have the energy of a damp receipt.', 'Even the mould wants a different roommate.', 'Your vibe has a cancellation fee.',
    'You are the human version of a reply-all.', 'I have met more charming parking tickets.', 'You chew like you are angry at the food.',
    'If I wanted to hear from you, I would have read your notes.', 'You are why the shampoo bottles have instructions.',
  ],
  fight: ['We are settling the thermostat debate.', 'Consider this constructive feedback.', 'This is for the yoghurt!', 'Nobody touches my labelled shelf!', 'Hold my towel.'],
  cook: ['The recipe says medium. I feel extreme.', 'Smoke is just seasoning with ambition.', 'How hot should the pan be? Yes.', 'Is the oil supposed to be on fire already?', 'I cook like I live: dangerously.'],
  grill: ['Rare, medium, or legally complicated?', 'Is the grill meant to be screaming?', 'Nothing says summer like singed eyebrows.'],
  snack: ['If it glows, it counts as a vegetable.', 'Someone wrote DO NOT EAT. A serving suggestion.', 'This container says "NOT YOURS". Delicious.', 'Mystery meat. My favourite genre.'],
  swim: ['Finally, a room without opinions.', 'I checked the water. It is definitely wet.', 'Nobody pee in the pool. I am looking at you.', 'The water is lovely. Suspiciously lovely.'],
  bath: ['A little self-care. What could possibly happen?', 'Bubble bath. Candles. Radio on the edge. Perfect.', 'Do not knock. I mean it.'],
  radio: ['Nothing relaxes me like electricity near water.', 'Turn it up! Wait, not like that—', 'A little jazz, a little voltage.', 'If I sing along, it drowns out the buzzing.'],
  repair: ['I watched half a tutorial. We are fine.', 'Red wire, blue wire. Rhymes with fire.', 'How hard can wiring be? Asking for my obituary.'],
  read: ['Chapter one: recognising warning signs.', 'This book is about a house exactly like ours. It does not end well.', 'Reading improves the mind. Mine is fine as it is.'],
  watch: ['Reality TV makes our house seem healthy.', 'A true crime show! Taking notes.', 'This documentary is about poisons. How relaxing.'],
  darkarts: ['The terms and conditions want my soul. Standard.', 'Step one: draw a circle. Step two: regret.', 'This forum has some VERY specific advice.'],
  devgame: ['It is not a bug. It is psychological horror.', 'Patch notes: removed the ending.', 'Three people will love this. One will review it.'],
  playtesting: ['Where is the save button? WHERE IS IT?', 'Level 40 is just a tax form.', 'I think the crow is judging me.'],
  gaslight: ['We never had a ladder. You imagined stairs.', 'That is not a red flag. That is mood lighting.', 'You are remembering it wrong. Again.', 'I never said that. Are you feeling alright?'],
  triangulate: ['I should not say this. Anyway, listen.', 'I am only telling you because I care. And because it is juicy.', 'Guess who has been talking about you?'],
  smear: ['It is not gossip if I made a slideshow.', 'I heard they steal from the fridge. I also started that.', 'Everybody knows. Now.'],
  lovebomb: ['We are soulmates. What is your PIN?', 'I have never met anyone like you. Sign here.', 'You are PERFECT. Do not change. Do not ask questions.'],
  lure: ['Come with me. Ignore the ominous music.', 'This way, darling. Mind the flames.', 'Follow me. Trust me. Mostly follow me.'],
  guilttrip: ['After everything I have almost done for you.', 'No, no, it is fine. I will just starve. Quietly. Loudly.', 'I am not upset. I am disappointed. And hungry.'],
  scene: ['I am being VERY reasonable, dramatically.', 'Everyone LOOK at how calm I am!', 'I need an audience for this breakdown.'],
  silent: ['...', '. . .', '*pointed silence*'],
  story: ['To understand my dream, we start in 2004.', 'Anyway, that was just the prequel.', 'Long story short: chapter seventeen.', 'Where was I? Oh yes, the beginning.', 'This next bit is really important. Also the bit after.'],
  joke: ['Our lease has a survival clause. Fine print.', 'Why did the roommate cross the road? The house was on fire.', 'I would tell you a poison joke, but you would not get it. Yet.'],
  drink: ['Try this. Family recipe.', 'Drink up. It is good for you. Briefly.', 'I made you a little something. Bottoms up.'],
  bake: ['Kneading is just strangling, but for bread.', 'Why is the kitchen so... foggy?', 'This flour gets EVERYWHERE.', 'Sourdough is a personality now.'],
  hair: ['Volume is a lifestyle.', 'One more coat. Maybe four.', 'This can says "keep away from flames". Cute.', 'My hair could stop a bullet.'],
  candlelit: ['Self-care is lighting things on fire, slowly.', 'This one is called "Burning Linen".', 'Candles make everything cosier. And flammable.'],
  lightcandles: ['I will be right back. Probably.', 'Candles are basically decorative fire.'],
  weeds: ['Die, dandelions, die!', 'Gardening is just controlled arson.', 'Is the lawn supposed to be smoking?', 'Nature must be punished.'],
  insultbikers: ['Scooters. SCOOTERS.', 'Posting our address was a power move.', 'What is the worst that could happen?'],
  beer: ['Easy, big fella. Have a beer.', 'You look thirsty. And terrifying.'],
  egg: ['Breakfast is served, neighbours!', 'Omelette you finish, but first: eggs.', 'This one is for the hedge complaint.'],
  gift: ['Peace offering incoming!', 'Please stop writing to the council.', 'Fruit! Nobody can be angry at fruit.'],
  rudevisit: ['Off my lawn. OFF.', 'We do not want any. Of anything. Ever.', 'Have you tried leaving?'],
  gasvisit: ['Welcome! Please, come closer.', 'Can I interest you in some air?'],
  hugvisit: ['Hug it out! Smell it out!', 'Come here, stranger.'],
  buyknives: ['Do they come in "extremely sharp"?', 'For the kitchen. Mostly.'],
  dance: ['This is my song. They are all my song.', 'Neighbours love a bass drop.', 'I dance like nobody is sleeping.'],
  blast: ['Sleep is for the weak.', 'Turn it up. No. UP.', 'It is not noise, it is culture.', 'Three in the morning is peak party time.'],
  whisper: ['Shhh. Sleep tight. Or not.', 'Psst. Wake up. No, sleep. No, wake up.', 'Your pillow knows what you did.', 'The walls asked me to tell you something.'],
  tickle: ['Coochie coochie DEATH.', 'Rise and shine, sunshine.', 'Tickle tax is due.'],
  airhorn: ['Good morning!', 'Is this thing on?', 'Rise and SHINE!', 'Fire drill! Not a real fire. Yet.'],
  barge: ['Oh, is this occupied?', 'Do not mind me. I live here too.', 'Quick question about the rota.'],
  chewloud: ['*crunch* *crunch* *CRUNCH*', 'These crisps are extra loud. On purpose.', 'Mouth closed is a myth.', 'Want some? Too late. *CRUNCH*'],
  stinkhug: ['Come here, you. Closer.', 'Hug it out. Smell it out.', 'I have been saving this hug for days. Literally.', 'Do not fight it. Nobody can fight it.'],
  fish: ['Fish in the shared microwave. Iconic.', 'Smells like the ocean. The dead bit.', 'Two minutes on high. Then the smell lives here forever.', 'It is called cuisine. Look it up.'],
  trash: ['The floor is a bin now.', 'Rubbish goes where rubbish wants.', 'Recycling? I am cycling it back onto the floor.', 'Somebody has a lot of tidying to do. Not me.'],
  toenails: ['Nobody look at the butter.', 'Snip. Snip. Oops.', 'That one went in the salad. Extra crunch.', 'Self-care at the dinner table.'],
  feral: ['Soap is a construct.', 'I am the smell now.', 'Deodorant is just a mask for your true self.', 'Day three. The socks can stand on their own.'],
  usetoilet: ['Occupied. For an hour.', 'This is my office now.', 'I have read every shampoo bottle. Twice.', 'Do not rush me. This is my only peace.'],
  clean: ['I did not sign up for this.', 'Who lives like this? Oh. Us.', 'I found a sock that is alive.', 'This stain has a pulse.'],
  flirtfire: ['Is it hot in here, or is it the house?', 'Take your time. Really. No rush.', 'Do you come to fires often?', 'Tell me about your hose. Slowly.'],
  coffee: ['Milk? Sugar? Alibi?', 'Sit, relax, stop looking at things.', 'Fresh pot. Nothing in it. Promise.'],
  charmdet: ['Officer, I am a very trustworthy person. Look at me.', 'Is that a warrant, or are you pleased to see me?', 'You look tired. Let me walk you to your car.'],
  ramble: ['So in 2004 I had this dream, right?', 'This part is crucial. So is the next part.', 'Where was I? Oh yes, the beginning.'],
  spoofradio: ['Dispatch has some urgent news for you. I wrote it.', 'All units, report to literally anywhere else.', 'Beep boop. Police business.'],
  gowork: ['Off to earn the money I spend on revenge.', 'Nobody touch anything. Especially the ladder.', 'Another day, another alibi.', 'Work is just a place where murder is frowned upon.'],
  workhome: ['I am working. The spreadsheet is open. Ignore the other tab.', 'Remote work: my commute is three metres and a grudge.', 'Camera off. Evil on.'],
  jobhunt: ['Skills: survival. References: dead.', 'Reason for leaving: explosion. Not my fault. Mostly.', 'Must be comfortable with a fast-paced, flammable environment.'],
  studychem: ['Chapter nine: things that go bang.', 'Lesson one: never lick the lab.', 'I am studying for peaceful reasons. Next question.'],
  studydiy: ['Red to red, blue to... hm.', 'Step one: turn it off. Step two: why?', 'It says "consult a professional". I AM the professional now.'],
  charm: ['Hello, gorgeous. Who, me? Yes, you.', 'Smile. Wider. Less teeth. More teeth.', 'The mirror agrees with me. As usual.'],
  code: ['It works and I do not know why.', 'It does not work and I do not know why.', 'Stack Overflow says I am wrong. Stack Overflow is wrong.'],
  studyastro: ['That star looks personal.', 'Space is big. My grudge is bigger.'],
  stargaze: ['Twinkle, twinkle, little meteor.', 'Somewhere up there, a rock has my name on it.', 'I wish, I wish... never mind, too dark.'],
  taunt: ['Come at me, cosmos!', 'Is that all you have got, sky?', 'Hit me with your best rock!'],
  toxin: ['A dash of this, a pinch of untraceable.', 'Bon appétit. Truly.'],
  sellcutlery: ['Lightly used. Very lightly. Mostly.', 'These forks have stories. Do not ask.'],
  npcgas: ['Just checking the gas. For safety.', 'This knob looks loose. Better make it looser.'],
  hideladder: ['Ladder? What ladder?', 'Somebody should look after this. In my room.'],
  sbd: ['Did anyone else hear a mouse? A big, wet mouse?', 'Nothing to see here. Plenty to smell.'],
  stoke: ['Cosy is a spectrum.', 'A little more. A little more. PERFECT.', 'Fire safety is a state of mind.'],
  crank: ['Tropical. Volcanic, even.', 'Who needs a sauna when you have me?'],
  light: ['Nothing says home like controlled fire.', 'Cosy season!'],
  blowcandles: ['Make a wish! Mine is fire insurance.', 'There. Safe. For now.'],
  mourn: ['They were... here. That is what I will say.', 'Gone too soon. But not soon enough.', 'I will never forget their... face. Probably.'],
  pizza: ['Extra cheese. Extra everything. Put it on their card.', 'Pizza is the only thing in this house that shows up on time.'],
  mail: ['Bills, bills, suspiciously heavy parcel.', 'Nothing for me. Nothing ticking. Good.'],
  slam: ['Not today, Satan. Or salesman.', 'Bye!'],
  doorchat: ['Lovely weather for it. For what? No reason.', 'Come in? Oh, you would not want to. Trust me.'],
  pamphlet: ['The end of the world? In this house? Tuesday.', 'Thank you. I will read it to someone slowly.'],
  charmcop: ['Officer. Is that a badge, or are you just pleased to see me?', 'Do you always look this heroic, or only on duty?'],
  answercop: ['I was at home, officer. With my alibi.', 'Where was I? Where were YOU?'],
  hacklock: ['Doors locked. For everyone. Especially you.', 'The house is in maintenance mode. Permanently.'],
  hackwires: ['Overclocking the whole house. For science.', 'Watch the lights. Watch them VERY closely.'],
  scheme: ['Posting anonymously. Very anonymously.', 'The forum and I have a plan.'],
  race: ['Last one out of the pool does the dishes.', 'On your marks. Get set. Drown.'],
  warm: ['Nothing warms the soul like a slightly unstable fire.', 'Toasty. Maybe too toasty.'],
  warmhands: ['Brr. Oh, that is better. Almost too better.', 'Fire: nature\'s radiator.'],
  stopmusic: ['Silence. Glorious, murderous silence.', 'Some of us have a lease to sleep through.'],
  toiletbrush: ['Brushing time!', 'Bristles are bristles.', 'Two minutes. Every tooth. Every corner of the bowl.'],
  slipper: ['YETER!', 'Catch!', 'You want to say that again?', 'This one has your name on it.'],
  apologise: ['I am so, so sorry. Truly. Mostly.', 'Can we start again? From before the thing?', 'I brought you a peace offering. It is an apology.'],
  breathe: ['Good morning! *HAAAAH*', 'Smell my breath. No reason.', 'Come closer. Closer. CLOSER.', 'Say ahh. No, I will. HAAAAH.'],
  note: ['Per my last extremely passive-aggressive note.', 'The dishes are not soaking. They are evolving.', 'Kindly. KINDLY. Underlined.'],
  narcissist: [
    'The lighting here does not respect my journey.', 'I am the main character. You are overheads.', 'Mirror, mirror — never mind, I already know.',
    'I would apologise, but I am never wrong.', 'Everyone here should be grateful I moved in.', 'My flaws are what make me perfect.',
    'Is this about me? It is usually about me.', 'I do not have enemies. I have audiences.', 'Humble? I invented humble. I am the best at it.',
  ],
  schemer: [
    'My alibi has an alibi.', 'I call it conflict optimisation.', 'Every friendship is a long con with snacks.',
    'I never lie. I edit the truth for length.', 'Trust is just a vulnerability with good PR.', 'Plan A was friendship. Plan B is better.',
    'I keep my friends close and my receipts closer.', 'Everyone here is a chess piece. I am the hand.', 'Rules are just suggestions with lawyers.',
  ],
  drama: [
    'I need privacy. And an audience.', 'Nobody panic until I have changed outfits.', 'This is the WORST day of my life. Today.',
    'I am fine. I am FINE. Does anyone want to hear why I am not fine?', 'Somebody breathed near my shelf.', 'I am not crying, I am performing.',
    'This house has no respect for my arc.', 'I have had a breakdown and a breakthrough. Before lunch.',
  ],
  vampire: [
    'Quick question. Do you have six hours?', 'I am an empath. Your energy is now mine.', 'You look tired. I will tell you about my problems.',
    'I am not needy. I just need everyone.', 'Could you hold this conversation? For the rest of your life?', 'I feel so drained. Come closer.',
    'Let me tell you about my feelings. All of them. Chronologically.',
  ],
  charmer: ['I am a catch. Read that as a warning.', 'Trust me. Terrible idea, but do it.', 'Everyone falls for me. Some of them literally.', 'I get away with everything. It is exhausting.'],
  hacker: ['Have you tried turning the household off?', 'I put the smart fridge on probation.', 'Your password is your birthday. It was.', 'I have root access to the toaster.'],
  slob: ['Soap is a scam by Big Soap.', 'I shower when it rains.', 'Germs are just friends you have not met yet.', 'My immune system has an immune system.'],
  // The named characters get their own material, including their take on particular situations ('id:topic').
  'asraa:arrival': ['Charming house. I will make it work. I make everything work.', 'Which room gets the best light? Mine. Decided.'],
  'asraa:gowork': ['Off to explain chemistry to a jury. Slowly.', 'Another day, another acquittal.'],
  'asraa:death': ['Natural causes. I will sign the report myself.', 'Such a shame. Pass the canapés.', 'Tragic. Truly. Anyway.'],
  'asraa:fire': ['This dress is flame retardant. I tested it. In court.', 'Somebody call my lawyer. Oh wait, that is me.'],
  'asraa:drink': ['Something bespoke, darling. You will love it. Briefly.', 'Drink up. Doctor\'s orders.'],
  'asraa:suspicious': ['Relax, everyone. I have an alibi for all of you.', 'Nobody suspects the expert witness. Nobody ever has.'],
  asraa: [
    'Technically I am a doctor. Of chemistry. Of consequences.', 'Relax, it is organic. Most poisons are.',
    'I am billing the law firm for this conversation.', 'Untraceable is my love language.', 'I have testified in forty trials. Never as the defendant.',
    'Beauty fades. Not mine, though. I am like wine.', 'Would you like a drink? It is very... bespoke.',
    'Objection. I am far too pretty to be guilty.', 'I did my thesis on almonds. Ask me why.', 'The coroner and I have an understanding.',
    'Nobody searches the handbag of the expert witness.', 'Chemistry is just cooking where the guests do not wake up.',
  ],
  'daniel:death': ['Respawn timer: never. Harsh.', 'That is not a bug. That is a feature.', 'Unsubscribed.'],
  'daniel:workhome': ['Commit message: "fixed everything, broke everything".', 'One more build. Then sleep. Then one more build.', 'My game has four fans. Three are bots. I love them all.'],
  'daniel:fire': ['Is the house overclocked?', 'I did not push that to production. Did I?'],
  'daniel:arrival': ['First thing: where is the router?', 'Nice house. Terrible Wi-Fi. I can fix one of those.'],
  daniel: [
    'My new game has no tutorial. Or mercy.', 'I am not antisocial. I am in early access.', 'The smart lock does what I tell it. Unlike people.',
    'Death keeps crashing on my machine.', 'I speedran the lease agreement.', 'This house has more bugs than my game. I put most of them there.',
    'Asraa, did you see my new build? It deletes people. Emotionally.', 'Immortality is just an extremely long session.',
  ],
  'adam:gowork': ['Off to call people during dinner. It is a calling.', 'Time to ring strangers about their car warranty.'],
  'adam:death': ['That reminds me of a story. Several, actually.', 'They never heard the end of my story. Nobody has.'],
  'adam:arrival': ['Hi! Have I told you about myself? Settle in.', 'New roommates! New audience!'],
  'adam:fire': ['This is like the time in 2003. Let me tell you about 2003.'],
  adam: [
    'So anyway, that reminds me of a story.', 'Do not worry, this one only has nine parts.', 'I will keep it short. That was a joke. It will not be short.',
    'Where was I? Right. 1997.', 'Have I told you about my sourdough? Settle in.', 'Pull up a chair. And a sleeping bag.',
    'Interesting fact about gravel: there are many.', 'And THAT is only the introduction.',
  ],
  gloria: [
    'Wait, let me find my good side. Both sides are my good side.', 'This kitchen would be so much more tragic with a ring light.',
    'I only eat food that photographs well.', 'My followers say I am relatable. I have never related to anything.',
    'Link in bio. Alibi in bio.', 'I am on a detox. From other people.', 'Do not tag me in the crime scene.',
    'Gaslight, gatekeep, get a brand deal.', 'Is this candid? Make it look candid.',
  ],
  'gloria:fire': ['Get my phone. GET MY PHONE. This is content.', 'Fire is SO on trend right now.', 'Nobody put it out until I have the shot!'],
  'gloria:death': ['Posting a tasteful tribute. With a filter.', 'Candle emoji. Crying emoji. Engagement.', 'RIP. Swipe up for my skincare routine.'],
  'gloria:arrival': ['Hi besties, welcome to my new house tour. Ignore the roommates.', 'The lighting in here is a crime.'],
  'gloria:gowork': ['Off to a photo shoot. Try not to die while I am famous.'],
  silas: [
    'This house? Low mileage. One careful owner. Several careless ones.', 'I can do you a great deal on your own funeral.',
    'Everything is negotiable. Especially the truth.', 'Trust me, I sell cars.', 'That noise? That is character.',
    'Sign here, here and here. Do not read that bit.', 'The warranty on this friendship expires today.',
    'I once sold a hearse to the person who needed it.',
  ],
  'silas:fire': ['Smoke damage adds value. Vintage.', 'I can shift this house by Friday. Sold as seen.'],
  'silas:death': ['Tragic. Anyway, their room is available. Great rate.', 'I will take the bed off your hands. Cash.'],
  'silas:gowork': ['Time to sell a lemon to a very nice family.', 'Off to the lot. Somebody out there needs a car with a past.'],
  'silas:fight': ['Final offer: I win.', 'No refunds!'],
  dolly: [
    'In the soap I would have an evil twin by now.', 'I have died on screen eleven times. I know the angles.',
    'Nobody said cut, so I am still in character.', 'Dramatic pause. ... Longer. ... There.', 'My agent says I have a very killable face.',
    'This is not a house, it is a set with plumbing.', 'Where is my close-up? I was promised a close-up.',
  ],
  'dolly:fire': ['FINALLY, a scene worthy of me!', 'Somebody fetch a smoke machine. Oh.'],
  'dolly:death': ['That should have been MY death scene.', 'Upstaged. By a corpse.', 'Nobody dies like that in episode one. Amateur.'],
  'dolly:cook': ['Fine, I will cook. But I am crying about it.', 'This is the saddest omelette ever filmed.'],
  'dolly:gowork': ['Off to the studio. I have two lines today. TWO.'],
  pete: [
    'Everything is flammable if you believe in it.', 'I do not have a problem. I have a lighter.', 'Safety goggles are for people who want to see.',
    'Smells like a bonfire. Oh wait, that is me.', 'My eyebrows grew back. Big mistake.', 'Candles are just fireworks with patience.',
    'I rate this house four matches out of five.',
  ],
  'pete:fire': ['Now THIS is a housewarming.', 'Look at those colours! Wait, that is the sofa.', 'Nobody touch it. It is perfect.'],
  'pete:light': ['Little more. Little more. Perfect.', 'Hello, old friend.'],
  'pete:gowork': ['Off to the fireworks shop. Staff discount, baby.'],
  'pete:death': ['Should have gone out with a bang. Amateurs.'],
  bertha: [
    'You are not on the list.', 'I bounce people for a living. Out of this life is just a bit further.', 'I have thrown out bigger men for smaller reasons.',
    'Say that again. Slower. Closer.', 'Dress code in this house: survive.', 'I do not do small talk. I do headlocks.',
    'Name? Not on the list. Lease? Also not on the list.',
  ],
  'bertha:fight': ['Oh, we are doing this? Good.', 'You picked the wrong bouncer.', 'Hold still. This will not take long.'],
  'bertha:gowork': ['Night shift. Somebody is getting thrown out tonight.'],
  'bertha:death': ['They are off the list now. For good.'],
  'bertha:hunger': ['Feed me or fight me.', 'I could eat a whole buffet. I have. They banned me.'],
  gus: [
    'Three beans. Three-bean chili. Nine consequences.', 'My chili has a warning label. I wrote it.', 'I am not gassy. I am seasoned.',
    "Grandma's recipe. Grandma is not with us. Because of the recipe.", 'Bless me, for I am about to sin. Stand back.',
    'The smoke alarm does not go off for smoke. It goes off for me.', 'Open a window. Actually, open the house.',
  ],
  'gus:gassy': ['Here it comes. Nobody light a match.', 'This one has a name. Its name is Gerald.', 'Stand back. I am about to be historic.'],
  'gus:cook': ['More beans. MORE.', 'The secret ingredient is more beans.'],
  'gus:death': ['Rest in peace. I will eat their leftovers.', 'Gone. But their chili lives on. In me.'],
  seance: [
    'The spirits say you owe me money.', 'I see a tall, dark stranger. It is a hearse.', 'Your aura is beige. I am so sorry.',
    'I predicted this conversation. It was better in my head.', 'The dead are chatty tonight. The living, less so.',
    'Your future is bright. Mostly the flames.', 'I charge by the minute. Even here.',
  ],
  'seance:death': ['Welcome to the other side! Please leave a review.', 'Their ghost is already complaining about the rent.', 'I will be in touch. Literally.'],
  'seance:fire': ['The spirits did say "hot" this week.', 'I saw this coming. I just did not mention it.'],
  'seance:stargaze': ['Mercury is in retrograde. So is your life expectancy.', 'The stars say: someone in this house. Not me.'],
  'seance:darkarts': ['Just a little light necromancy.', 'The spirits accept cash, card and souls.'],
  vincent: [
    'Why buy a toothbrush when the house already has a big one?', 'It is a toothbrush with a longer handle. Ergonomic.',
    'Four out of five dentists have stopped returning my calls.', 'Minty? No. Earthy. With notes of plumbing.',
    'Germs are just friends you have not met yet.', 'I gargle with pool water. Chlorine is basically mouthwash.',
    'I am a dental hygienist. I know exactly what I am doing. That is the scary part.', 'Floss is for people with commitment issues.',
    'Come closer, I have a secret. HAAAAH.', 'My breath has a fragrance note. The note is "drain".',
  ],
  'vincent:toiletbrush': ['Top to bottom. Then the teeth.', 'Ah, fresh. Well. Fresh-ish.', 'The bristles have seen things. Now my teeth have too.', 'Two minutes, twice a day, one bowl.'],
  'vincent:usetoilet': ['Toilet and toothbrush in one room. Efficient.', 'While I am here, might as well do my teeth.'],
  'vincent:breathe': ['Good MORNING!', 'Say ahh. No, I will say it. HAAAAH.', 'Smell that? That is dedication.', 'Morning breath? This is all-day breath.'],
  'vincent:arrival': ['Lovely place. Where do you keep the toilet brush? Asking for my teeth.', 'Which bathroom is mine? I have a routine.'],
  'vincent:death': ['Shame. Their toothbrush is free now. Not that I need one.', 'Gone. Probably should have brushed more. Like me.'],
  'vincent:gowork': ['Off to clean other people\'s teeth. Not mine. Mine are fine.', 'Time to lecture strangers about flossing.'],
  'vincent:fire': ['Great, now my breath smells of smoke. An improvement.'],
  'vincent:hunger': ['I will eat anything. Anything. Do not test me.'],
  nermin: [
    'Sit down. Eat. Why are you so thin? Eat!', 'You call this tea? Real çay takes patience. You have none.',
    'Shoes inside? INSIDE? Allah Allah.', 'I have two slippers and no patience.', 'My slipper has never missed. Ask my nephews.',
    'In my day we respected our elders. Also, we ducked.', 'I did not raise you, but I will discipline you.',
    'The neighbours will talk. Let them. I have more slippers.', 'Who left crumbs on my sofa cover? Confess now.',
    'You look tired. Eat börek. Then clean.',
  ],
  'nermin:slipper': ['YETER!', 'Terlik geliyor!', 'This is for your own good.', 'Duck. Too late.'],
  'nermin:arrival': ['This house needs a proper clean. And proper food. And me.', 'Who lives like this? Take your shoes off.'],
  'nermin:gowork': ['Off to the börek shop. Nobody touch my slippers.', 'Six in the morning. The dough will not knead itself.'],
  'nermin:cook': ['Watch and learn. No, not like that. Like THIS.', 'More butter. Always more butter.'],
  'nermin:death': ['Rest in peace. You never once took your shoes off.', 'I will bring börek to the funeral. Too much börek.'],
  'nermin:fight': ['Come here. COME HERE.', 'You think I cannot fight in slippers?'],
  'nermin:fire': ['My börek! Save the börek!'],
};

export const REPLIES = {
  chat: ['Can this meeting be an email?', 'I miss living alone. With my problems.', 'Wow. Great. Anyway.', 'I will think about it. I will not.'],
  insult: ['I am putting that in the group chat.', 'Bold words from someone who owns that towel.', 'Noted. Revenge scheduled.', 'Say that again and see what happens to your yoghurt.'],
  story: ['I have aged during this sentence.', 'Blink twice if the story has an ending.', 'Please. I have a family. Somewhere.', 'Is there an intermission?'],
  gaslight: ['I am fairly sure I remember a ladder.', 'I need a second opinion. From a plant.', 'Am I... imagining things?'],
  lovebomb: ['This feels like a subscription trap.', 'Nobody has ever said that to me. Suspicious.', 'Is this a pyramid scheme?'],
  tickle: ['STOP. HAHA. I WILL END YOU. HAHA.', 'I was having a lovely dream!', 'You are dead to me. HAHAHA.'],
  barge: ['KNOCK! Have you heard of KNOCKING?!', 'GET OUT GET OUT GET OUT.', 'Delete that photo. DELETE IT.'],
  chewloud: ['I can hear your teeth thinking.', 'Chew with your mouth closed or I close it for you.'],
  stinkhug: ['Why are you damp?', 'I can taste you. Why can I taste you?'],
  note: ['Your handwriting also needs a rota.', 'I left a note about your note.', 'A laminated note? You psychopath.'],
  joke: ['I should not laugh. I cannot stop.', 'That is so wrong. Tell it again.'],
  drink: ['It smells like almonds. Is that normal?', 'Cheers! Why are you not drinking?'],
  slipper: ['OW! Right on the forehead!', 'How is she so ACCURATE?', 'I did not even do anything! This time.', 'Why does it always hit?'],
  apologise: ['Hmph.', 'Say it again. Slower.', 'We will see.'],
  breathe: ['WHAT HAVE YOU BEEN EATING?!', 'My eyebrows are melting.', 'I can SEE the smell.', 'Is that... toilet? WHY IS IT TOILET?', 'I can taste colours. Brown ones.'],
};
